import {
  Building2,
  ChartLine,
  FileText,
  FlaskConical,
  Grid3x2,
  HandCoins,
  Package,
  Receipt,
  Scale,
  ShoppingCart,
  TrendingUp,
  Users,
  Wallet,
  ShoppingBag,
  User,
  Store,
} from "lucide-react";

export const navigationItems = [
  {
    id: "analytics",
    title: "Analytics",
    href: "/",
    icon: ChartLine,
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN"],
  },
  // {
  //   id: "quick-access",
  //   title: "Quick Access",
  //   href: "/quick-access",
  //   icon: Grid3x2,
  //   type: "single",
  // },
  {
    id: "trading",
    title: "Trading",
    icon: ShoppingCart,
    type: "group",
    defaultOpen: true,
    roles: ["SUPER_ADMIN", "ADMIN"],
    children: [
      {
        id: "account",
        title: "Accounts",
        href: "/account",
        icon: User,
        type: "single",
        roles: ["SUPER_ADMIN", "ADMIN"],
      },

      {
        id: "sale",
        title: "Whole Sale",
        href: "/sale",
        icon: ShoppingBag,
        type: "single",
        roles: ["SUPER_ADMIN", "ADMIN"],
      },
      {
        id: "transactions",
        title: "Recovery",
        icon: HandCoins,
        type: "single",
        href: "/transactions",
        roles: ["SUPER_ADMIN", "ADMIN"],
      },
      {
        id: "expense-head",
        title: "Expenses",
        icon: Receipt,
        type: "single",
        href: "/expense-head",
        roles: ["SUPER_ADMIN", "ADMIN"],
      },

      {
        id: "reports",
        title: "Reports",
        icon: FileText,
        href: "/reports",
        type: "single",
        roles: ["SUPER_ADMIN", "ADMIN"],
      },
    ],
  },

  {
    id: "user-recovery",
    title: "Recovery",
    icon: HandCoins,
    type: "single",
    href: "/transactions",
    roles: ["USER"],
  },
  {
    id: "local-sale",
    title: "Local Sale",
    href: "/local-sale",
    icon: ShoppingBag,
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN", "USER"],
  },

  {
    id: "local-sale-reports",
    title: "Local Sale Reports",
    icon: FileText,
    href: "/local-sale-reports",
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN", "USER"],
  },
  {
    id: "shop",
    title: "Shop",
    icon: Store,
    href: "/shop",
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN",],
  },
  {
    id: "shop-report",
    title: "Shop Report",
    icon: FileText,
    href: "/shop/reports",
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN"],
  },
  {
    id: "farming",
    title: "Farming",
    icon: Building2,
    type: "group",
    defaultOpen: false,
    roles: ["SUPER_ADMIN", "ADMIN"],
    children: [
      {
        id: "add-product",
        title: "Add Product",
        href: "/add-product",
        icon: Package,
      },
      {
        id: "add-unit",
        title: "Add Unit",
        href: "/add-unit",
        icon: Scale,
      },
      {
        id: "floc-management",
        title: "Floc Management",
        href: "/floc-management",
        icon: FlaskConical,
      },
      {
        id: "unit-expense",
        title: "Unit Expense",
        href: "/unit-expense",
        icon: Wallet,
      },
      {
        id: "unit-income",
        title: "Unit Income",
        href: "/unit-income",
        icon: TrendingUp,
      },
      {
        id: "trading",
        title: "Trading",
        href: "/trading",
        icon: ShoppingCart,
        type: "single",
      },

      {
        id: "reports",
        title: "Reports",
        icon: FileText,
        href: "/reports",
        type: "single",
      },
    ],
  },
  {
    id: "userManagement",
    title: "User Management",
    href: "/user_management",
    icon: Users,
    type: "single",
    roles: ["SUPER_ADMIN", "ADMIN"],
  },
];
